"""Add image_url to Project

Revision ID: 6cb568bb15aa
Revises: cc5ea8f77030
Create Date: 2024-07-31 20:39:53.294068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb568bb15aa'
down_revision = 'cc5ea8f77030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
